replicaCount: 1

image:
  repository: cluster.loc:5000/rs-algo-bot
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: {}

envSecretName: rs-algo-screener-secrets

podAnnotations: {}

service: {}

serviceAccount: {}

ingress: {}

resources:
  requests:
    cpu: 25m
    memory: 1Mi
  limits:
    cpu: 150m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 40
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  nodeType: storage

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - storage

tolerations: []

podSecurityContext: {}