---
- name: Deploy RS-ALGO-BOT
  hosts: all
  roles:
    #SHARED

    - { role: "deployment/git/roles" }
    # - { role: "deployment/mongodb-bot/roles/" }
    #PROD
    - { role: "rs_algo_bot/deployment/prod/numbars-eurusd-m15/roles" }
    - { role: "rs_algo_ws_server/deployment/prod/roles/" }

    #DEV
    # numbars
    # - { role: "rs_algo_bot/deployment/dev/numbars/numbars-eurchf-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbars/numbars-eurusd-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbars/numbars-gbpeur-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbars/numbars-usdcad-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbars/numbars-usdchf-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbars/numbars-usdjpy-m15/roles" }
    
    # - { role: "rs_algo_ws_server/deployment/dev/roles/" }

    # # numbarsdis
    # - { role: "rs_algo_bot/deployment/dev/numbarsdis/numbars-eurchf-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbarsdis/numbars-eurusd-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbarsdis/numbars-gbpeur-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbarsdis/numbars-usdcad-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbarsdis/numbars-usdchf-m15/roles" }
    # - { role: "rs_algo_bot/deployment/dev/numbarsdis/numbars-usdjpy-m15/roles" }
    # server
 
    
    



