---
- name: Deploy RS-ALGO-BOT
  hosts: all
  roles:
    #SHARED

    - { role: "deployment/git/roles" }
    #- { role: "deployment/mongodb-bot/roles/" }

    #PROD
    - { role: "rs_algo_ws_server/deployment/prod/roles/" }
    - { role: "rs_algo_bot/deployment/prod/bb-reversals/eurusd/roles" }
    - { role: "rs_algo_bot/deployment/prod/bb-reversals/usdchf/roles" }
    - { role: "rs_algo_bot/deployment/prod/bb-reversals/usdjpy/roles" }
    - { role: "rs_algo_bot/deployment/prod/bb-reversals/gbpusd/roles" }

    #DEV
    # bb-reversals
    - { role: "rs_algo_bot/deployment/dev/bb-reversals/eurusd/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversals/gbpusd/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversals/usdchf/roles" }
    - { role: "rs_algo_bot/deployment/dev/bb-reversals/usdjpy/roles" }
    

    # bb-reversals-sell
    # - { role: "rs_algo_bot/deployment/dev/bb-reversals-sell/eurusd/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversals-sell/gbpusd/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversals-sell/usdchf/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversals-sell/usdjpy/roles" }
    - { role: "rs_algo_ws_server/deployment/dev/roles/" }

    # # bb-reversalsdis
    # - { role: "rs_algo_bot/deployment/dev/bb-reversalsdis/eurchf/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversalsdis/eurusd/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversalsdis/gbpeur/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversalsdis/usdcad/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversalsdis/usdchf/roles" }
    # - { role: "rs_algo_bot/deployment/dev/bb-reversalsdis/usdjpy/roles" }
    # server
 
    
    



