---
- name: Deploy RS-ALGO-BOT
  hosts: all
  roles:
    - { role: "deployment/git/roles" }
    # - { role: "deployment/mongodb-bot/roles/" }
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-bitcoin-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-ethereum-m15/roles" }
    #- { role: "rs_algo_bot/deployment/bbmb/bbmb-xrp-m15/roles" }
    # bbmb
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-audusd-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-eurchf-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-eurusd-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-gbpusd-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-usdchf-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-usdjpy-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbmb/bbmb-gbpcad-m15/roles" }
    #- { role: "rs_algo_bot/deployment/bbmb/bbmb-nzdusd-m15/roles" }
    #- { role: "rs_algo_bot/deployment/bbmb/bbmb-chfjpy-m15/roles" }
    # bbrev
    - { role: "rs_algo_bot/deployment/bbrev/bbrev-audusd-m15/roles" }

    - { role: "rs_algo_bot/deployment/bbrev/bbrev-eurchf-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbrev/bbrev-eurusd-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbrev/bbrev-gbpusd-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbrev/bbrev-usdchf-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbrev/bbrev-usdjpy-m15/roles" }
    - { role: "rs_algo_bot/deployment/bbrev/bbrev-gbpcad-m15/roles" }
    #- { role: "rs_algo_bot/deployment/bbrev/bbrev-nzdusd-m15/roles" }
    #- { role: "rs_algo_bot/deployment/bbrev/bbrev-chfjpy-m15/roles" }
    # server
    - { role: "rs_algo_ws_server/deployment/roles/" }


