ENV: "Backtesting"
EXECUTION_MODE: "BotBackTest"
WS_SERVER_URL: "ws://rs-algo-ws-server-backtest"
WS_SERVER_PORT: "9000"
WS_SERVER_STR: "ws_bot_backtest"
HEARTBEAT_INTERVAL: "60"
LAST_DATA_TIMEOUT: "100"
MARKET_CLOSED_RETRY: "300"
DISCONNECTED_RETRY: "1"
MARKET: "Forex"
SYMBOL: "USDJPY"
TIME_FRAME: "M15"
HIGHER_TIME_FRAME: "H4"
STRATEGY_TYPE: "LongShortMTF"
STRATEGY_NAME: "BB_Reversals_Backtest_D"
EQUITY: "1000"
ORDER_SIZE: "0.01"
LEVERAGE: "30.0"
ORDER_WITH_SPREAD: "true"
PIP_VALUE: "0.0001"
PIPS_PROFIT_TARGET: "30"
PIPS_STOP_LOSS: "50"
PIPS_MARGIN: "1"
RISK_REWARD_RATIO: "1"
COMMISSION: "0.0"
MAX_BUY_ORDERS: "1"
MAX_SELL_ORDERS: "1"
MAX_STOP_LOSSES: "1"
MAX_PENDING_ORDERS: "3"
STOP_LOSS_SPREAD: "true"
ORDERS_OVERWRITE: "true"
NON_PROFITABLE_OUTS: "true"
ORDER_VALID_UNTIL_BARS: "10"
ATR_STOPLOSS: "5"
ATR_PROFIT_TARGET: "2.5"
INITIAL_BARS: "20"
NUM_BARS: "50000"
MAX_PREVIOUS_BARS: "50"
NEXT_DELETE: "5"
MAX_HISTORICAL_POSITIONS: "15"
ORDER_ENGINE: "bot"
PRICE_SOURCE: "close"
ORDER_ACTIVATION_SOURCE: "close"
WAIT_FOR_NEW_ENTRY: "true"
WAIT_FOR_NEW_EXIT: "false"
CANDLES_UNTIL_NEW_ENTRY: "5"
TRADING_DIRECTION: "true"
LOGARITHMIC_SCANNER:  "false"
MIN_PRICE: "-100."
EQUAL_THRESHOLD: "0.018"
SLOPE_DEVIATION_THRESHOLD: "1"
PARALLEL_LINES_THRESHOLD: "5"
MAX_PATTERN_DAYS: "3"
MAX_PATTERN_ACTIVATED_DAYS: "3"
MIN_PATTERN_BARS: "10"
MINIMUM_PATTERN_TARGET: "15"
PATTERNS_WINDOW_SIZE: "4"
AVG_VOLUME_DAYS: "30"
MIN_VOLUME: "25000000"
DIVERGENCES_WINDOW_SIZE: "3"
PATTERNS: "false"
PATTERNS_MAX_POINTS: "1000"
PATTERNS_MIN_POINTS: "3"
DIVERGENCES: "false"
DIVERGENCES_MIN_POINTS: "2"
INDICATORS: "true"
CANDLE_TYPES: "true"
INDICATORS_ATR: "true"
INDICATORS_MACD: "false"
INDICATORS_STOCH: "false"
INDICATORS_BB: "true"
INDICATORS_BBW: "false"
INDICATORS_RSI: "true"
INDICATORS_EMA_A: "true"
INDICATORS_EMA_B: "true"
INDICATORS_EMA_C: "true"
HORIZONTAL_LEVELS: "false"
LOCAL_MIN_PROMINENCE: "0.020"
EXTREMA_MIN_PROMINENCE: "0.050"
LOCAL_PROMINENCE_MIN_DISTANCE: "10"
EXTREMA_PROMINENCE_MIN_DISTANCE: "20"
KERNEL_PRICE_SMOOTHING: "false"
KERNEL_REGRESSION_BANDWIDTH: "0.05"
DIVERGENCE_MIN_PROMINENCE: "0.02"
DIVERGENCE_PROMINENCE_MIN_DISTANCE: "10"
EMA_A: "5"
EMA_B: "13"
EMA_C: "21"
BB_PERIOD: "20"
BB_MULTIPLIER : "2"
MACD_A: "12"
MACD_B: "26"
MACD_C: "9"
EMA_PERCENTAGE_DIS: "0.01"
GAP_THRESHOLD: "1.02"
HEAD_AND_SHOULDERS_THRESHOLD: "0.03"
HORIZONTAL_LEVELS_THRESHOLD: "1"
MIN_HORIZONTAL_LEVELS_OCCURENCES: "2"
PRICE_BREAK_CHECKPOINTS: "3"
STREAM_SUBSCRIBE: "true"
SEND_UPDATE_ON_STREAM: "false"
BACKEND_BACKTEST_PRICING_ENDPOINT: "http://rs-algo-backend/api/backtest/price/"