ENV: "production"
EXECUTION_MODE: "Bot"
WS_SERVER_HOST: "0.0.0.0:"
WS_SERVER_PORT: "9000"
WS_SERVER_NAME: "WS Socket Server"
WS_SERVER_STR: "ws_bot"
LAST_DATA_TIMEOUT: "65"
MARKET_CLOSED_RETRY: "300"
HEARTBEAT_INTERVAL: "10000"
KEEPALIVE_INTERVAL: "30000"
DISCONNECTED_RETRY: "60"
BROKER_URL: "wss://ws.xtb.com/real"
BROKER_STREAM_URL: "wss://ws.xtb.com/realStream"
STREAM_SUBSCRIBE: "true"
NUM_BARS: "4080"
MAX_PREVIOUS_BARS: "50"
NEXT_DELETE: "5"
MAX_HISTORICAL_POSITIONS: "15"
ORDER_ACTIVATION_SOURCE: "close"
MONGO_BOT_DB_NAME: "bot-db"
MONGO_BOT_DB_URI: "@mongodb-bot:27017/bot-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"
DB_BOT_COLLECTION: "bots"