replicaCount: 1

image:
  repository: cluster.loc:5000/rs-algo-ws-server-backtest
  pullPolicy: Always
  tag: "latest"

imagePullSecrets:
 - name: docker-credentials 

envSecretName: rs-algo-screener-secrets

podAnnotations: {}

service:
  type: ClusterIP
  port: 9000
  targetPort: 9000
  metadata:
    name: rs-algo-ws-server-backtest
    labels:
      app: rs-algo-ws-server-backtest

serviceAccount: {}

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts: []
  
  tls: []

resources:
  requests:
    cpu: 50m
    memory: 1Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 90
  # targetMemoryUtilizationPercentage: 80

nodeSelector:
  nodeType: worker

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: nodeType
          operator: In
          values:
          - worker

tolerations: []

podSecurityContext: {}