ENV: "production"
ENVIRONMENT: "production"
LOKI_ENDPOINT: "http://logging-loki.logging.svc.cluster.local:3100"
EXECUTION_MODE: "Bot"
WS_SERVER_HOST: "0.0.0.0:"
WS_SERVER_PORT: "9000"
BROKER: "oanda"
BROKER_USERNAME: ""
BROKER_PASSWORD: ""
OANDA_API_TOKEN: ""
OANDA_ACCOUNT_ID: ""
OANDA_ENVIRONMENT: "live"
DB_USERNAME: ""
DB_PASSWORD: ""
MONGO_BOT_DB_NAME: "bot-db"
MONGO_BOT_DB_URI: "mongodb-bot:27017/bot-db?authSource=admin&readPreference=primary&retryWrites=true&directConnection=true&ssl=false"
DB_BOT_COLLECTION: "bots"
NUM_BARS: "1200"
KEEPALIVE_INTERVAL: "30000"
HEARTBEAT_INTERVAL: "60"
LAST_DATA_TIMEOUT: "100"
