[package]
name = "rs_algo_bot"
version = "0.1.0"
authors = ["pmagaz <magazpablo@gmail.com>"]
edition = "2024"

[dependencies]
anyhow = "1.0.98"
thiserror = "2.0"
tokio = { version = "1.44", features = ["rt-multi-thread", "macros"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
serde_qs = "0.12.0"
dotenv = "0.15.0"
chrono = { version = "0.4.40", features = ["serde"] }
async-trait = "0.1.83"
dyn-clone = "1.0.17"
round = "0.1.2"
futures = "0.3.31"
env_logger = "0.11"
log = "0.4"
futures-util = "0.3.31"
rs_algo_shared = { path = "../../rs_algo_shared", features = ["broker", "websocket"] }

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
strip = true
lto = true
