// pub mod bollinger_bands_reversals;
// pub mod bollinger_bands_reversals_mt_macd;
// pub mod ema_50200;
// pub mod macd_dual;
//pub mod bollinger_bands_middle_band;
pub mod bollinger_bands_reversals;
pub mod bollinger_bands_reversals_atr;
pub mod ema_scalping;
pub mod num_bars_atr;
pub mod num_bars_atr_dis;
// pub mod ema_scalping2;
pub mod strategy;
