// pub mod bollinger_bands_reversals;
// pub mod bollinger_bands_reversals_mt_macd;
// pub mod ema_50200;
// pub mod macd_dual;
//pub mod bollinger_bands_middle_band;
pub mod bollinger_bands_reversals_buy_exit;
// pub mod bollinger_bands_reversals_buy_exit_hv;
// pub mod bollinger_bands_reversals_buy_exit_noclose;
// pub mod bollinger_bands_reversals_buy_exit_noclose_2;
pub mod strategy;
